_id: spc_af1c5f17a6654e4fabb6daa9209faf13
type: ApiSpec
parentId: wrk_17b857c2a99f4cbd9c8952aa0ebcab8c
modified: 1641428349490
created: 1638308055978
fileName: TCC API
contents: >-
  openapi: 3.0.0

  info:
    description: API
    version: 1.0.0
    title: API
  tags:
    - name: auth
      description: Endpoints for authentication
    - name: testimonial
      description: Endpoints for testimonials
    - name: comment
      description: Endpoints for comment
  paths:
    /auth/login:
      post:
        tags:
          - auth
        summary: Login
        description: ''
        requestBody:
          $ref: "#/components/requestBodies/AuthLogin"
        responses:
          "200":
            description: Ok
            content:
              application/json:
                example:
                  _id: 0
                  name: Foo Bar
                  email: foo@bar.com
                  createdAt: <timestamp>
                  updatedAt: <timestamp>
                  token: <token>
          '404':
            description: Not found
            content:
              application/json:
                example:
                  error: Usuário não encontrado!
    /auth/store:
      post:
        tags:
          - auth
        summary: Sign Up
        description: ''
        requestBody:
          $ref: '#/components/requestBodies/AuthStore'
        responses:
          '201':
            description: Created
            content:
              application/json:
                example:
                  name: Foo Bar
                  email: foobar@gmail.com
                  _id: 0
                  createdAt: '2021-11-30T23:29:32.932Z'
                  updatedAt: '2021-11-30T23:29:32.932Z'
                  __v: 0
    /testimonials:
      get:
        tags:
          - testimonial
        summary: Get all testimonials
        description: ''
        security:
          - bearerAuth: []
        parameters:
          - name: limit
            in: query
            description: Quantity of testimonials returned 
            required: false
            explode: true
            schema:
              type: integer
              default: 10
          - name: page
            in: query
            description: Number of page to skip before starting to collect the result set
            required: false
            explode: true
            schema:
              type: integer
              default: 1
        responses:
          '200':
            description: Ok
            content:
              application/json:
                example:
                  - _id: 0
                    user: 0
                    title: Foo
                    text: FooBar
                    createdAt: '2022-01-05T15:00:42.226Z'
                    updatedAt: '2022-01-05T15:00:42.226Z'
                    __v: 0
      post:
        tags:
          - testimonial
        summary: Store one testimonial
        description: ''
        security:
          - bearerAuth: []
        requestBody:
          $ref: '#/components/requestBodies/Testimonial'
        responses:
          '201':
            description: Created
    '/testimonials/{id}':
      get:
        tags:
          - testimonial
        summary: Get one testimoniall
        description: Get one testimonial by id
        security:
          - bearerAuth: []
        parameters:
           - name: id
             in: path
             description: Testimonial id
             required: true
             schema:
               type: integer
        responses:
          '200':
            description: Ok 
            content:
              application/json:
                example:
                  _id: 0
                  user: 0
                  title: Foo
                  text: Foobar
                  createdAt: '2022-01-05T15:00:42.226Z'
                  updatedAt: '2022-01-05T15:00:42.226Z'
                  __v: 0
    '/testimonials/user/{id}':
      get:
        tags:
          - testimonial
        summary: Get all testimonials by user
        description: ''
        security:
          - bearerAuth: []
        parameters:
          - name: id
            in: path
            description: The owner ID of the testimonials
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Ok
            content:
              application/json:
                example:
                  - _id: 0
                    user: 0
                    title: string
                    text: string
                    createdAt: '2022-01-05T15:20:11.558Z'
                    updatedAt: '2022-01-05T15:20:11.558Z'
                    __v: 0
    /comments:
      get:
        tags:
          - comment
        summary: Get all comments from a testimonial
        description: ''
        security:
          - bearerAuth: []
        parameters:
          - name: testimonial
            in: query
            description: Testimonial id
            required: true
            explode: true
            schema:
              type: string
        responses:
          '200':
            description: Ok
            content:
              application/json:
                example:
                  - _id: 0
                    user: 0
                    testimonial: 0
                    comment: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eleifend
                      lobortis enim.
                    createdAt: '2022-01-05T23:26:34.292Z'
                    updatedAt: '2022-01-05T23:26:34.292Z'
                    __v: 0
      post:
        tags:
          - comment
        summary: Store one comment
        description: ''
        security:
          - bearerAuth: []
        requestBody:
          $ref: '#/components/requestBodies/Comment'
        responses:
          '201':
            description: Created
    '/comments/{id}':
      delete:
        tags:
          - comment
        summary: Delete one comment
        description: ''
        security:
          - bearerAuth: []
        parameters:
          - name: id
            in: path
            description: Comment id
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Ok
  servers:
    - url: http://localhost:3333/v1
  components:
    securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT  # optional, arbitrary value for documentation purposes
    requestBodies:
      AuthStore:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthStore"
        required: true
      AuthLogin:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthLogin"
        required: true
      Testimonial:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Testimonial"
        required: true
      Comment:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Comment"
        required: true
    schemas:
      AuthStore:
        type: object
        required:
          - name
          - email
          - password
        properties:
          name:
            type: string
          email:
            type: string
          password:
            type: string
      AuthLogin:
        type: object
        required:
          - email
          - password
        properties:
          email:
            type: string
          password:
            type: string
      Testimonial:
        type: object
        required:
          - user
          - title
          - text
        properties:
          user:
            type: string
          title:
            type: string
          text:
            type: string
      Comment:
        type: object
        required:
          - user
          - testimonial
          - comment
        properties:
          user:
            type: string
          testimonial:
            type: string
          comment:
            type: string
      ApiResponse:
        type: object
        properties:
          code:
            type: integer
            format: int32
          type:
            type: string
          message:
            type: string
contentType: yaml
